version: '3.2'

services:
  db:
    restart: always
    image: postgres
    container_name: noteapp_db
    volumes:
      - type: volume
        source: dbdata
        target: /pg_data
    ports:
      - "8001:5432"
  es:
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    build:
      context: ./noteapp/docker_compose/elasticsearch/
      dockerfile: Dockerfile
    container_name: noteapp_es
    restart: always
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
  kibana:
    labels:
      com.example.service: "kibana"
      com.example.description: "Data visualisation and for log aggregation"
    build:
      context: ./noteapp/docker_compose/kibana/
      dockerfile: Dockerfile
    container_name: noteapp_kibana
    ports:
      - "5601:5601"
    depends_on:
      - es
  logstash:
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    build:
      context: ./noteapp/docker_compose/logstash/
      dockerfile: Dockerfile
    container_name: noteapp_logstash
    volumes:
      - ./noteapp/docker_compose/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./noteapp/docker_compose/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5959:5959"
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
    - es
  # filebeat:
  #   labels:
  #     com.example.service: "filebeat"
  #     com.example.description: "For sending log files to logstash"
  #   build:
  #     context: ./noteapp/docker_compose/filebeat/
  #     dockerfile: Dockerfile
  #   container_name: noteapp_filebeat
  #   volumes:
  #     - ./noteapp/logs:/usr/share/filebeat/logs
  #   environment:
  #     - LOGSTASH_URL=logstash:5044
  #   expose:
  #     - "5044"
  #   depends_on:
  #     - logstash
  django_web:
    container_name: noteapp_django_web
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build:
      context: ./noteapp/docker_compose/django/
      dockerfile: Dockerfile
    image: noteapp_django_web:1.0
    restart: always
    depends_on:
      - db
      - es
      - kibana
      - logstash
      # - filebeat
    command: ["./docker_compose/django/wait_for_postgres.sh"]
    environment:
      - LOGSTASH_HOST=logstash
    expose:
      - "5959"
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
    volumes:
      - ./noteapp:/app

volumes:
  dbdata:
  esdata:
