FROM docker.elastic.co/logstash/logstash:5.4.3

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# Add your logstash plugins setup here
RUN logstash-plugin update logstash-input-beats
