FROM logstash:5

# copy local file from folder to logstash container for execution
COPY logstash.conf /etc/logstash/conf.d/logstash.conf

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# execute command for application
CMD ["-f", "etc/logstash/conf.d/"]
