FROM docker.elastic.co/beats/filebeat:5.4.3

# Add your logstash plugins setup here
# Example: RUN logstash-plugin update logstash-input-beats

COPY filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN chown filebeat /usr/share/filebeat/filebeat.yml
USER filebeat

